### ISSUE TITLE
Is Python path the only issue in my build?

### ISSUE THREAD

**Issue by xianglo** [MyCryptoHQ/MoneroVision#26]
Building: C:\Program Files\nodejs\node.exe C:\Users\Xianglo\Desktop\MoneroVision\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.14.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\which\\which.js:68:19)\n
at E (C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE
gyp verb check python version `C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.2\r\n"
gyp verb could not find "C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE". checking python launcher
gyp verb could not find "C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Xianglo\Desktop\MoneroVision\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Xianglo\Desktop\MoneroVision\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Xianglo\\Desktop\\MoneroVision\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Xianglo\Desktop\MoneroVision\node_modules\node-sass
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wtzb** [comment]
Hi there @xianglo!

Judging by `gyp ERR! stack Error: Can't find Python executable "C:\Users\Xianglo\AppData\Local\Programs\Python\Python37\python.EXE", you can set the PYTHON env variable.`, Python is probably what's causing this.

Unfortunately, I'm unsure how to solve this on Windows, but I'm sure there's guides out there on how to fix your paths.
